name: README

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: pwsh

      - name: Instalar dependências do Node.js
        run: |
          npm install
        shell: pwsh

      - name: Start Server
        run: |
          Start-Process -NoNewWindow -FilePath "node" -ArgumentList "index.js"
        shell: pwsh

      - name: Wait for 15 seconds
        run: |
          Start-Sleep -Seconds 15
        shell: pwsh

      - name: Atualizar README
        run: |
          $latestUpdates = "`n## Últimas Atualizações`nAtualizado em: $(Get-Date)"
          $branches = git branch -r | Where-Object {$_ -notmatch 'HEAD|main'} | ForEach-Object { "- $($_.Split('/')[1])" }
          $latestUpdates += "`n" + ($branches -join "`n")
          (Get-Content -Path README.md) -replace '<!--START_SECTION:latest-updates-->.*<!--END_SECTION:latest-updates-->', "<!--START_SECTION:latest-updates-->$latestUpdates`n<!--END_SECTION:latest-updates-->" | Set-Content -Path README.md
        shell: pwsh

      - name: Commit e Push
        run: |
          git add README.md
          git commit -m "docs: atualiza readme $(Get-Date)"
          git push origin main
        shell: pwsh

      - name: Stop Server
        run: |
          Stop-Process -NoNewWindow -FilePath "node" -ArgumentList "index.js"
        shell: pwsh
